// The judges page's words (/how-it-works). Facts come from the listener-memory spec and decision 009
// (rm-playlist-v2), docs/HACKATHON.md, and the reply templates in src/lib/speech.ts. Keep them in step.
// Example replies are real playlist data (Oct 4, 2026), spoken with spokenSaved / spokenDigest wording; never invent shows or counts.

export const HOW_IT_WORKS = {
  eyebrow: "For hackathon judges",
  headline: "One sentence, five services, and a station that remembers you.",
  lead: "Alexa+ keeps the current conversation. Amazon leaves memory across sessions to each add-on, so Radio Commons keeps it: the artists you follow, the list you were just shown, and what changed since you last asked.",
  builtBy: "Built by Tarik Moody, Director of Strategy and Innovation at Radio Milwaukee for nearly 20 years: a station building for stations.",
  sections: {
    demo: "The two-session demo",
    flow: "One sentence, five services",
    memory: "What we remember, and how to erase it",
    give: "Try a donation (sandbox)",
    alexa: "Built on Alexa+",
    aws: "Built on AWS",
    status: "Status",
  },
  sessionsData: "Real data from the playlist, as of October 4, 2026",
  sessions: [
    {
      label: "Session 1 · Tuesday",
      title: "“Save this.”",
      setup: "A listener hears a song on HYFIN and asks Alexa+ to save it. One reply covers the save, Apple Music, the follow, the next local show and the station’s own story.",
      says: "Alexa, save this.",
      reply: "Saved \"No ID\" by Tank & The Bangas to your 88Nine Finds, and I'm adding it to Apple Music. I'll keep an eye out for Tank & The Bangas — they play Majestic Theatre in Madison on Tuesday, October 20, and we have their Studio Milwaukee story.",
      note: "The song played on HYFIN. Shows are looked for in Milwaukee first; with no Milwaukee date, the next one is in Madison. The story is the station’s “Studio Milwaukee Session: Tank & The Bangas.” “Save number 3” works too: we remember the numbered list on screen for 30 minutes, on any device.",
    },
    {
      label: "Session 2 · days later",
      title: "“What’s new for me?”",
      setup: "A new conversation. Alexa+ has forgotten the first one; Radio Commons hasn’t. The digest is built from what the station’s DJs actually played, who is playing in town, and the station’s own stories.",
      says: "Alexa, what’s new for me?",
      reply: "Since your last visit: Rhythm Lab played Tank & The Bangas 10 times, 88Nine 3 times and HYFIN twice. Tank & The Bangas plays Majestic Theatre in Madison on Tuesday, October 20.",
      note: "A show in the next week comes first, then the artists the station played most, then new station stories, then Apple Music news. Alexa speaks the top three items; an Echo Show also shows a card with a tile per artist. A brand-new listener with nothing followed hears the station’s current picks instead.",
    },
  ],
  services: [
    { name: "Playlist", does: "Identifies the play: “number 3” from the list on screen, or the song and artist." },
    { name: "Finds", does: "Saves it to the listener’s 88Nine Finds, in the station’s playlist database." },
    { name: "Apple Music", does: "Adds it to the listener’s library. A background job, so the reply never waits." },
    { name: "Concerts", does: "Follows the artist and finds their next show from AXS and Ticketmaster listings, Milwaukee first." },
    { name: "Backstory", does: "Finds the station’s stories about the artist. A background job, refreshed daily." },
  ],
  flowNote: "The slow parts run off the listener’s path: background jobs store their results, and the next reply reads what is stored. The reply only mentions what is ready.",
  remembered: [
    { what: "Your saved songs", detail: "Artist, title, station and when you saved them. Your 88Nine Finds." },
    { what: "The artists you follow", detail: "Including ones you follow by saving their song, and ones you told us to stop following, so a later save doesn’t follow them again." },
    { what: "The last list you were shown", detail: "Used for 30 minutes so “save number 3” means the song you saw, then replaced by the next list." },
    { what: "When you last asked what’s new", detail: "So the digest tells you only what changed since then." },
  ],
  erase: "Say “Alexa, delete my Finds” and all of it is erased, along with the Apple Music connection. It lives in one database, next to the songs it points to, so there is one place to erase it.",
  notStored: "We remember exact facts, not things said in passing. No voice recordings, no email address and no name are stored with them.",
  memoryWhy: "Why our own tables and not an AI memory service: the things worth remembering are exact song and artist ids, and the playlist database already holds the songs, artists and concerts they point to.",
  give: {
    intro: "Say “I want to support Radio Milwaukee”: a monthly membership by voice, paid with Amazon Pay, cancelled by voice. It is Amazon Pay’s sandbox (a practice mode), so no real money moves, ever.",
    steps: [
      "In the simulator, say “I want to support Radio Milwaukee” and tap a level, or open /give?tier=ga-monthly.",
      "Main Floor and up come with a thank-you gift. Keep it and pick a t-shirt size, or choose “No gift — all of it goes to the station”. With a gift, Amazon Pay asks for the shipping address on its own page. Nothing actually ships in the demo.",
      "On the Amazon Pay page, sign in with the sandbox test buyer from the Devpost testing instructions. Card ending 1111 always works; 3434 shows a decline.",
      "The thank-you page shows the receipt and where the gift would ship (name, city and state). Press “Simulate next month” to see the second monthly charge.",
      "In the linked simulator, say “what’s new for me” and it mentions the membership.",
      "Then say “cancel my Radio Milwaukee membership”, then “yes”.",
    ],
    tip: "Use a private or incognito window, or sign out of Amazon first. A real Amazon login is refused with “Your order can’t be completed with this account.”",
    credentials: "The test buyer’s email and password are in the Devpost testing instructions, not on this page.",
    link: { label: "Open the give page", href: "/give?tier=ga-monthly" },
  },
  alexa: [
    { title: "Add-on manifest", text: "alexa/addon-package/addon.json: Amazon’s add-on manifest, with an MCP integration pointing Alexa+ at our endpoint and example phrases such as “Save that song” and “What’s new for me”. Deployed with npm run alexa:deploy (Amazon’s alexa-ai CLI)." },
    { title: "MCP 2025-11-25, Streamable HTTP", text: "One endpoint, /api/mcp, with tools for stories, the weekly briefing, events, songs, the 88Nine schedule, Finds, listener memory and membership. Tools that touch a listener’s own data need a linked account." },
    { title: "Account linking, per Amazon’s spec", text: "Clerk as the sign-in server: OAuth 2.1 with PKCE (S256), refresh tokens, the add-on sends the RFC 8707 resource parameter during account linking, and RFC 9728 protected-resource metadata at /.well-known/oauth-protected-resource." },
    { title: "MCP Apps cards", text: "Every answer works by voice alone, and on an Echo Show it also returns a card built to Amazon’s MCP design guide: song lists with artwork and 30-second previews, and the digest." },
  ],
  aws: [
    { title: "Amazon Bedrock", text: "Claude Haiku 4.5 through the Converse API does two jobs. In Backstory it pulls people, places and actions out of every transcript, each with a word-for-word quote that is checked before an editor sees it (backstory convex/aws/extract.ts). In the simulator it plays Alexa+, calling the real MCP server with tool use (src/lib/sim/brain.ts)." },
    { title: "Amazon Polly", text: "The simulator’s voice. Replies stream through a short-lived signed link, so the first words play about half a second after the reply is ready (src/lib/sim/tts.ts)." },
    { title: "Amazon Location Service", text: "Map pictures on the Echo Show cards and the pan-and-zoom map (the key stays on the server: src/app/api/map/route.ts, src/lib/map/staticMap.ts); geocoding and place details (phone, website, hours) for every place in a story (backstory convex/aws/geocode.ts, placeDetails.ts); 154 of 155 event-guide venues pinned for about $1.25." },
    { title: "Amazon Transcribe and S3", text: "Backstory’s fallback transcriber (backstory convex/aws/transcribe.ts). A 19-episode bake-off chose Deepgram as the default for local names; the AWS path stays one setting away (TRANSCRIBER=transcribe)." },
  ],
  limits: [
    "Station stories appear only for artists Radio Milwaukee has covered, such as its premieres and Studio Milwaukee sessions.",
    "No proactive notifications: Amazon doesn’t document them for add-ons, so the digest waits for the listener to ask.",
    "Amazon isn’t giving hackathon participants the Alexa+ developer tools, so judges can try every tool in our simulator, which calls the same MCP server.",
  ],
  status: [
    { feature: "Save a song to Finds and Apple Music", state: "Live", detail: "Verified end to end" },
    { feature: "Song recall and recent songs (artwork, 30-second previews)", state: "Live", detail: "88Nine, HYFIN, Rhythm Lab, 414 Music" },
    { feature: "Credits and the story behind a song", state: "Live", detail: "" },
    { feature: "Alexa+ account linking and the add-on manifest", state: "Live", detail: "Per Amazon’s spec" },
    { feature: "Listener memory in the playlist database", state: "Live", detail: "Follows, last list, digest data, Backstory stories, daily refresh" },
    { feature: "Support Radio Milwaukee: monthly membership with Amazon Pay, cancel by voice (sandbox, no real money)", state: "Live", detail: "" },
    { feature: "Station stories: This Bites, Uniquely Milwaukee, Ladies First, Radio Milwaukee Artist Interviews, Music Premieres, Studio Milwaukee Sessions", state: "Live", detail: "Find by what you remember, play, ask a detail question; every story published by an editor" },
    { feature: "Weekly station briefing: “What’s new at Radio Milwaukee this week?” from the 88Nine newsletter", state: "Live", detail: "Each item opens its story, Concert Picks or the page (since October 5)" },
    { feature: "88Nine schedule: who’s on, when a show airs", state: "Live", detail: "Since October 5" },
    { feature: "Artist and title search", state: "In this release", detail: "About two weeks of plays (today: about a day)" },
    { feature: "“Save number 3” on any device", state: "In this release", detail: "" },
    { feature: "The one-sentence save reply", state: "In this release", detail: "Save, Apple Music, follow, next show, station story" },
    { feature: "Follow and stop following", state: "In this release", detail: "" },
    { feature: "“What’s new for me?” and its card", state: "In this release", detail: "" },
  ],
  statusDate: "October 4, 2026",
} as const;
